import mongoose from "mongoose";

/**
 * Mongoose Schema for Restaurant Bookings
 */
const bookingSchema = new mongoose.Schema(
  {
    // Unique identifier generated by uuidv4 in the controller
    bookingId: {
      type: String,
      required: true,
      unique: true,
    },
    customerName: {
      type: String,
      required: true,
      trim: true,
    },
    customerEmail: {
      type: String,
      trim: true,
      lowercase: true,
    },
    numberOfGuests: {
      type: Number,
      required: true,
      min: 1,
    },
    bookingDate: {
      type: Date,
      required: true,
    },
    bookingTime: {
      type: String,
      required: true,
    },
    cuisinePreference: {
      type: String,
      trim: true,
    },
    specialRequests: {
      type: String,
      trim: true,
    },
    // Stores raw JSON data from the OpenWeatherMap API
    weatherInfo: {
      type: Object,
      default: {},
    },
    // Restricted to specific values to maintain data integrity
    seatingPreference: {
      type: String,
      enum: ["indoor", "outdoor"],
      default: "indoor",
    },
    status: {
      type: String,
      enum: ["confirmed", "pending", "cancelled"],
      default: "confirmed",
    },
  },
  { timestamps: true },
);

const Booking = mongoose.model("Booking", bookingSchema);

export default Booking;
